### ISSUE TITLE
Crash on assert inside `if` statement

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier-python#4]
Minimal repro (I think):

```python
def func():
    if condition:
        pass
    else:
        assert something
        another_statement()
```

```
test.py: TypeError: Cannot read property 'length' of undefined
    at FastPath.map (.../node_modules/prettier/src/common/fast-path.js:119:34)
    at printBody (.../node_modules/prettier-python/src/printer/index.js:119:50)
    at printIf (.../node_modules/prettier-python/src/printer/index.js:154:30)
    at parts.push.path.map.p (.../node_modules/prettier-python/src/printer/index.js:167:30)
    at FastPath.map (.../node_modules/prettier/src/common/fast-path.js:124:19)
    at printIf (.../node_modules/prettier-python/src/printer/index.js:167:21)
    at Object.genericPrint [as print] (.../node_modules/prettier-python/src/printer/index.js:453:14)
    at genericPrint (.../node_modules/prettier/src/main/ast-to-doc.js:97:18)
    at comments.printComments.p (.../node_modules/prettier/src/main/ast-to-doc.js:39:14)
    at Object.printComments (.../node_modules/prettier/src/main/comments.js:1102:19)
    at printGenerically (.../node_modules/prettier/src/main/ast-to-doc.js:37:22)
    at FastPath.map (.../node_modules/prettier/src/common/fast-path.js:124:19)
    at printBody (.../node_modules/prettier-python/src/printer/index.js:119:50)
    at Object.genericPrint [as print] (.../node_modules/prettier-python/src/printer/index.js:225:34)
    at genericPrint .../node_modules/node_modules/prettier/src/main/ast-to-doc.js:97:18)
    at comments.printComments.p (.../node_modules/prettier/src/main/ast-to-doc.js:39:14)
    at Object.printComments (.../node_modules/prettier/src/main/comments.js:1102:19)
    at printGenerically (.../node_modules/prettier/src/main/ast-to-doc.js:37:22)
    at FastPath.map (.../node_modules/prettier/src/common/fast-path.js:124:19)
    at printBody (.../node_modules/prettier-python/src/printer/index.js:119:50)
    at Object.genericPrint [as print] (.../node_modules/prettier-python/src/printer/index.js:191:22)
    at genericPrint .../node_modules/prettier/src/main/ast-to-doc.js:97:18)
```

**Comment by vjeux** [comment]
Something is happening with this line:

```js
concat(path.map(p => printIf(p, print, true), "orelse"))
```

If I replace it with

```js
concat(path.map(print, "orelse"))
```

it doesn't crash anymore. The reason I believe it's happening is that path is stateful and there's only one true variable that's mutated, something must be holding on to it after it's been mutated and reading from the wrong one.

**Comment by vjeux** [comment]
```js
  const isElse =
    parent.ast_type === 'If' &&
      parent.orelse.length > 0 &&
      !(parent.orelse.length === 1 && parent.orelse[0].ast_type !== "If") &&
      parent.orelse.indexOf(n) !== -1;
```

fixes the problem. It's not super elegant but the ast structure is pretty wonky and we've been doing this a lot in the prettier codebase with success.
